%{
#include<stdio.h>
#include<string.h>

int keywords=0,identifiers=0,comments=0;
int words=0,lines=0,spaces=0;

char *kw[]={
"auto","break","case","char","const","continue","default","do",
"double","else","enum","extern","float","for","goto","if","int",
"long","register","return","short","signed","sizeof","static",
"struct","switch","typedef","union","unsigned","void","volatile","while"
};

int isKeyword(char *str)
{
    int i;
    for(i=0;i<32;i++)
        if(strcmp(str,kw[i])==0)
            return 1;
    return 0;
}
%}

ID [a-zA-Z_][a-zA-Z0-9_]*

%%

"//".* {comments++;}

"/*"([^*]|\n|\*+[^*/])*\*+"/" {comments++;}

\n {lines++;}

[ \t] {spaces++;}

{ID} {
    words++;
    if(isKeyword(yytext))
        keywords++;
    else
        identifiers++;
}

[0-9]+ {words++;}

. ;

%%

int yywrap()
{
    return 1;
}

int main()
{
    printf("Reading Input File...\n\n");

    yylex();

    printf("\n========= RESULT =========\n");
    printf("Comments    : %d\n",comments);
    printf("Keywords    : %d\n",keywords);
    printf("Identifiers : %d\n",identifiers);
    printf("Words       : %d\n",words);
    printf("Lines       : %d\n",lines+1);
    printf("Spaces      : %d\n",spaces);

    return 0;
}
